apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.fullname }} #i27-eureka-dev
spec:
  replicas: {{ .Values.replicas.default }}
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      imagePullSecrets:
      - name: private-jfrog-registry #the secret with this name should be present in the cluster
      # This is how we can pass the secrets in the deploy file
      containers:
        - name: {{ .Values.name }}
        # the below image should be dynamically change based on the devlelopment 
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
